Resolver: $$ \int_{0.1}^{0.5} \int_{x^3}^{x^2} e^{y/x} dy dx $$ 

In [70]:
import numpy as np
import matplotlib.pyplot as plt

In [71]:
coeff = np.loadtxt("coeff.dat")
print(coeff)

[[ 2.          0.57735027  1.        ]
 [ 2.         -0.57735027  1.        ]
 [ 3.          0.77459667  0.55555556]
 [ 3.          0.          0.88888889]
 [ 3.         -0.77459667  0.55555556]
 [ 4.          0.86113631  0.34785485]
 [ 4.          0.33998104  0.65214515]
 [ 4.         -0.33998104  0.65214515]
 [ 4.         -0.86113631  0.34785485]
 [ 5.          0.90617985  0.23692689]
 [ 5.          0.53846931  0.47862867]
 [ 5.          0.          0.56888889]
 [ 5.         -0.53846931  0.47862867]
 [ 5.         -0.90617985  0.23692689]]


In [72]:
#definiendo los l`imites internos de integraci`on

def c(x):
    value = x**3
    return value

def d(x):
    value = x**2
    return value

def f(x,y):
    value = np.e**(y/x)
    return value

In [73]:
def DoubleGauss(a,b,c,d,f,n,m):
    #pesos (w_i,w_j) y raices (z_i,t_j)
    
    w_i = []
    z_i = []
    
    for i in range(0,coeff.shape[0]):
        if(n == int(coeff[i][0])):
            w_i.append(coeff[i][2])
            z_i.append(coeff[i][1])
    
    w_j = []
    t_j = []
    
    for j in range(0,coeff.shape[0]):
        if(m == int(coeff[j][0])):
            w_j.append(coeff[j][2])
            t_j.append(coeff[j][1])
    
    #Integral
    sum_i = 0
    
    for i in range(0,n):
        x_i = 0.5*((b-a)*z_i[i] + a + b)
        
        sum_j = 0
        
        for j in range(0,m):
            y_j = 0.5*((d(x_i)+c(x_i))*t_j[j] + c(x_i) +d(x_i))
            
            sum_j += f(x_i,y_j)*w_i[i]*w_j[j]
            
        sum_i += sum_j*(d(x_i)-c(x_i))
    
    value = sum_i*0.25*(b-a)
    
    return value
        
    
    

In [74]:
print(DoubleGauss(0.1,0.5,c,d,f,5,5))

0.033643448159522985


In [79]:
def c(x):
    value = 1
    return value

def d(x):
    value = 1.5
    return value

def f(x,y):
    value = np.log(x+2*y)
    return value

In [80]:
print(DoubleGauss(1.4,2.0,c,d,f,5,5))

0.4101271396849226
