In [260]:
import numpy as np

In [261]:
A  = [[1,2,5,8],[5,4,6,0],[2,2,8,-1],[8,6,9,5]]
A = np.array(A)
print(A)

B = [1,8,5,5]
B = np.array(B)

[[ 1  2  5  8]
 [ 5  4  6  0]
 [ 2  2  8 -1]
 [ 8  6  9  5]]


In [262]:
def row_pivote(A,fil,col):
    max_value = max(A[fil:,col])
    min_value = min(A[fil:,col])
    #return max_value
    if (abs(max_value)>abs(min_value)):
        pivote = max_value
    else:
        pivote = min_value
    for i in range(0,A.shape[0]):
        if (A[i][col])==pivote:
            fila_pivote = i
    return fila_pivote

def TriangularSuperior(A):  

    n = A.shape[0]
    ATriangSup = np.zeros((n,n))
    ATriangSup[:,0:n] = A
    
    #Matriz triangular superior por eliminacion Gaussiana
    i = 0  #Contador sobre filas
    j = 0  #Contador sobre columnas
    
    for h in range(j,n):        
        fila_pivote = row_pivote(ATriangSup,i,h)
        pivote = ATriangSup[fila_pivote][h]
        
        if (fila_pivote != i):
            ATriangSup[[fila_pivote,i]] = ATriangSup[[i,fila_pivote]]   #Permutar filas
        
        for k in range(i+1,n):
            x = - ATriangSup[k][h]/pivote
            ATriangSup[k] = ATriangSup[k] + x*ATriangSup[i]
            
        i = i + 1
        j = j + 1
  
    return ATriangSup

print(TriangularSuperior(A))

[[ 8.  6.  9.  5.]
 [ 0.  1.  4.  7.]
 [ 0.  0.  4. -5.]
 [ 0.  0.  0. -5.]]


In [263]:
def Det(A):
    n = A.shape[0]
    ATriangSup = TriangularSuperior(A)
    diagprod = 1.0
    for i in range(0,n):
        diagprod *= ATriangSup[i][i]
    return diagprod

print(Det(A))
    

-214.0


In [264]:
def InverseMatrix(A):
     
    #Matriz aumentada
    n = A.shape[0]
    
    Ainv = np.zeros((n,2*n))
    
    Ainv[:,0:n] = A
    
    #Aumentada con la identidad
    for i in range(0,n):
        Ainv[i][i+n] = 1.0
    
    #return Ainv
    #Matriz triangular superior por eliminacion Gaussiana
    
    i = 0  #Contador sobre filas
    j = 0  #Contador sobre columnas
    
    for h in range(j,n-1):                       #No se consideran columnas de I
        fila_pivote = row_pivote(Ainv,i,h)
        pivote = Ainv[fila_pivote][h]
        
        if (fila_pivote != i):
            Ainv[[fila_pivote,i]] = Ainv[[i,fila_pivote]]   #Permutar filas
        
        for k in range(i+1,n):
            x = - Ainv[k][h]/pivote
            Ainv[k] = Ainv[k] + x*Ainv[i]
            
        i = i + 1
        j = j + 1
        
       
    for i in range(0,n):
        Ainv[i] = Ainv[i]/Ainv[i][i]      

    #return Ainv     
    
    for j in range(n-1,0,-1):
        for i in range(j-1,-1,-1):
            x = - Ainv[i][j]
            Ainv[i] = Ainv[i] + x*Ainv[j]
 
    #return Ainv
    
    AINV = np.zeros((n,n))
    AINV = Ainv[:,n:2*n] 
            
    return AINV

In [265]:
np.set_printoptions(precision=5)
print(InverseMatrix(A))

[[-0.46729 -1.03738  0.18692  0.78505]
 [ 0.64019  1.91121 -0.55607 -1.13551]
 [-0.03738 -0.24299  0.21495  0.1028 ]
 [ 0.04673 -0.19626 -0.01869  0.1215 ]]


In [266]:
#Prueba
L = np.matmul(A,InverseMatrix(A))
print(L)


[[ 1.00000e+00  4.44089e-16  0.00000e+00  0.00000e+00]
 [-4.44089e-16  1.00000e+00  0.00000e+00  0.00000e+00]
 [ 2.22045e-16  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  4.44089e-16  1.00000e+00]]
