In [93]:
import numpy as np

In [94]:
A  = [[-1,-2,2],[-5,-4,-6],[5,2,8]]
A = np.array(A)
print(A)

B = [1,8,5,5]
B = np.array(B)

[[-1 -2  2]
 [-5 -4 -6]
 [ 5  2  8]]


In [95]:
def row_pivote(A,fil,col):
    max_value = max(A[fil:,col])
    min_value = min(A[fil:,col])
    #return max_value
    if (abs(max_value)>abs(min_value)):
        pivote = max_value
    else:
        pivote = min_value
    for i in range(0,A.shape[0]):
        if (A[i][col])==pivote:
            fila_pivote = i
    return fila_pivote

def TriangularSuperiorPerm(A):  

    n = A.shape[0]
    ATriangSup = np.zeros((n,n))
    ATriangSup[:,0:n] = A
    
    #Matriz triangular superior por eliminacion Gaussiana
    i = 0  #Contador sobre filas
    j = 0  #Contador sobre columnas
    permut = 0.0
    
    for h in range(j,n):        
        fila_pivote = row_pivote(ATriangSup,i,h)
        pivote = ATriangSup[fila_pivote][h]
        
        if (fila_pivote != i):
            ATriangSup[[fila_pivote,i]] = ATriangSup[[i,fila_pivote]] #Permutar filas
            permut = permut + 1.0
        
        for k in range(i+1,n):
            x = - ATriangSup[k][h]/pivote
            ATriangSup[k] = ATriangSup[k] + x*ATriangSup[i]
            
        i = i + 1
        j = j + 1
  
    Return = [ATriangSup,permut]
    
    return Return

print(TriangularSuperior(A))

[array([[-5., -4., -6.],
       [ 0., -2.,  2.],
       [ 0.,  0.,  2.]]), 2.0]


In [96]:
def Det(A):
    n = A.shape[0]
    ATriangSup = TriangularSuperiorPerm(A)[0]
    diagprod = 1.0
    for i in range(0,n):
        diagprod *= ATriangSup[i][i]
    
    Sign = (-1)**TriangularSuperiorPerm(A)[1]
    
    return diagprod*Sign

print(Det(A))
    

20.0


In [97]:
def InverseMatrix(A):
     
    #Matriz aumentada
    n = A.shape[0]
    
    Ainv = np.zeros((n,2*n))
    
    Ainv[:,0:n] = A
    
    #Aumentada con la identidad
    for i in range(0,n):
        Ainv[i][i+n] = 1.0
    
    #return Ainv
    #Matriz triangular superior por eliminacion Gaussiana
    
    i = 0  #Contador sobre filas
    j = 0  #Contador sobre columnas
    
    for h in range(j,n-1):                       #No se consideran columnas de I
        fila_pivote = row_pivote(Ainv,i,h)
        pivote = Ainv[fila_pivote][h]
        
        if (fila_pivote != i):
            Ainv[[fila_pivote,i]] = Ainv[[i,fila_pivote]]   #Permutar filas
        
        for k in range(i+1,n):
            x = - Ainv[k][h]/pivote
            Ainv[k] = Ainv[k] + x*Ainv[i]
            
        i = i + 1
        j = j + 1
        
       
    for i in range(0,n):
        Ainv[i] = Ainv[i]/Ainv[i][i]      

    #return Ainv     
    
    for j in range(n-1,0,-1):
        for i in range(j-1,-1,-1):
            x = - Ainv[i][j]
            Ainv[i] = Ainv[i] + x*Ainv[j]
 
    #return Ainv
    
    AINV = np.zeros((n,n))
    AINV = Ainv[:,n:2*n] 
            
    return AINV

In [98]:
np.set_printoptions(precision=5)
print(InverseMatrix(A))

[[-1.   1.   1. ]
 [ 0.5 -0.9 -0.8]
 [ 0.5 -0.4 -0.3]]


In [99]:
#Prueba
L = np.matmul(A,InverseMatrix(A))
print(L)


[[1.00000e+00 0.00000e+00 1.11022e-16]
 [0.00000e+00 1.00000e+00 1.11022e-16]
 [0.00000e+00 0.00000e+00 1.00000e+00]]
