In [37]:
import numpy as np

In [45]:
A = [[0,1,0],[0,0,1],[2,-5,4]]
A = np.array(A)
B = [0,0,0]
B = np.array(B)

In [46]:
def Mprod(A,B):
    if (A.shape[1] == B.shape[0]):
        C = np.zeros((A.shape[1],B.shape[0]))
        
        for i in range(0,A.shape[0]):
            
            for j in range(0,B.shape[1]):
                
                sum = 0
                for k in range(0,A.shape[1]):
                    sum += A[i][k]*B[k][j]
                C[i][j] = sum
        return C
    
def Mtraz(A):
    if (A.shape[0] == A.shape[1]):
        sum = 0
        for i in range(0,A.shape[0]):
            sum += A[i][i]
        return sum
    
    
def row_pivote(A,fil,col):
    max_value = max(A[fil:,col])
    min_value = min(A[fil:,col])
    #return max_value
    if (abs(max_value)>abs(min_value)):
        pivote = max_value
    else:
        pivote = min_value
    for i in range(0,A.shape[0]):
        if (A[i][col])==pivote:
            fila_pivote = i
    return fila_pivote




def GaussSolver(A,B):
    
    ####################
    
    #Matriz aumentada
    n = A.shape[0]
    m = A.shape[1]
    
    AB = np.zeros((n,m+1))
    
    AB[:,0:m] = A
    
    for i in range(0,len(B)):
        AB[i][m] = B[i]
    
    #return AB
    
    #############
    #Eliminacion Gaussiana
    
    i = 0  #Contador sobre filas
    j = 0  #Contador sobre columnas
    
    for h in range(j,m-1):                       #No se considera la columna B
        fila_pivote = row_pivote(AB,i,h)
        pivote = AB[fila_pivote][h]
        
        if (fila_pivote != i):
            AB[[fila_pivote,i]] = AB[[i,fila_pivote]]   #Permutar filas
        
        for k in range(i+1,n):
            x = - AB[k][h]/pivote
            AB[k] = AB[k] + x*AB[i]
            
        i = i + 1
        j = j + 1
        
    return AB

In [54]:
#Valores propios de matrices 3x3
def eigenvalue(A):
    AA = Mprod(A,A)
    AAA = Mprod(A,AA)
    
    a0 = 1/6 * (Mtraz(A)**3 + 2*Mtraz(AAA) - 3*Mtraz(A)*Mtraz(AA))
    a1 = -1/2 * (Mtraz(A)*Mtraz(A)-Mtraz(AA))
    a2 = Mtraz(A)
    a3 = -1.0
    
    coefficients = [a3,a2,a1,a0]
    eigenvalues = np.roots(coefficients)        #Halla raices
    
    ###Solo para este ejemplo se toman los valores reales!!!!
    
    return np.real(eigenvalues)                #Toma partes reales solamente

valprop = eigenvalue(A)
    
print(eigenvalue(A))
    

[2. 1. 1.]


In [55]:
def eigenvector(A,L):        #L es eigenvector
    matrix = A - L*np.identity(3)
    return(GaussSolver(matrix,B))


print(eigenvector(A,2))    
print(eigenvector(A,1))

[[-2.  1.  0.  0.]
 [ 0. -4.  2.  0.]
 [ 0.  0.  0.  0.]]
[[ 2.  -5.   3.   0. ]
 [ 0.  -1.5  1.5  0. ]
 [ 0.   0.   0.   0. ]]
