In [1]:
import numpy as np

In [64]:
A = [[1,2,5,8],[5,4,6,0],[2,2,8,-1],[8,6,9,5]]
A = np.array(A)
print(A)

B = [1,8,5,5]
B = np.array(B)

[[ 1  2  5  8]
 [ 5  4  6  0]
 [ 2  2  8 -1]
 [ 8  6  9  5]]


In [65]:
print(A[:,1:]) #

[[ 2  5  8]
 [ 4  6  0]
 [ 2  8 -1]
 [ 6  9  5]]


In [66]:
#Retorna fila del pivote de una columna
def row_pivote(A,fil,col):
    max_value = max(A[fil:,col])
    min_value = min(A[fil:,col])
    #return max_value
    if (abs(max_value)>abs(min_value)):
        pivote = max_value
    else:
        pivote = min_value
    for i in range(0,A.shape[0]):
        if (A[i][col])==pivote:
            fila_pivote = i
    return fila_pivote
    
    
#print(row_pivote(A,0,2)) 

In [68]:
def GaussSolver(A,B):
    
    ####################
    
    #Matriz aumentada
    n = A.shape[0]
    m = A.shape[1]
    
    AB = np.zeros((n,m+1))
    
    AB[:,0:m] = A
    
    for i in range(0,len(B)):
        AB[i][m] = B[i]
    
    #return AB
    
    #############
    #Eliminacion Gaussiana
    
    i = 0  #Contador sobre filas
    j = 0  #Contador sobre columnas
    
    for h in range(j,m-1):                       #No se considera la columna B
        fila_pivote = row_pivote(AB,i,h)
        pivote = AB[fila_pivote][h]
        
        if (fila_pivote != i):
            AB[[fila_pivote,i]] = AB[[i,fila_pivote]]   #Permutar filas
        
        for k in range(i+1,n):
            x = - AB[k][h]/pivote
            AB[k] = AB[k] + x*AB[i]
            
        i = i + 1
        j = j + 1
  
    #return AB
     ######################
        
    #Solucion    
    x_sol = np.zeros(n)
    for i in range(n-1,-1,-1):
        
        if (i == n-1):
            x_sol[i] = AB[i][m] / AB[i][i]
        else:
            sum = 0
            for j in range(i+1,m):
                sum += AB[i][j]*x_sol[j]
            x_sol[i] = (AB[i][m] -sum) / AB[i][i]
            
    return x_sol
    
    
print(GaussSolver(A,B))

[-3.90654206  7.47196262 -0.39252336 -1.00934579]
