In [54]:
import numpy as np

In [55]:
A = [[2,3,4],[5,4,6],[1,0,9]]
A = np.array(A)
#convertir a Arreglo
B = [[2,3,4],[5,4,6],[1,0,9]]
B = np.array(B)

print(A)
print("")
print(B)


[[2 3 4]
 [5 4 6]
 [1 0 9]]

[[2 3 4]
 [5 4 6]
 [1 0 9]]


In [56]:
def Msum(A,B):

    if (A.shape == B.shape):
        
        C = np.zeros(A.shape)
        
        for i in range(0,A.shape[0]):
            for j in range(0,A.shape[1]):
                C[i][j] = A[i][j] + B[i][j]
        return C

print(Msum(A,B))
print("")
print(A+B)

[[ 4.  6.  8.]
 [10.  8. 12.]
 [ 2.  0. 18.]]

[[ 4  6  8]
 [10  8 12]
 [ 2  0 18]]


In [57]:
def Mprod(A,B):
    if (A.shape[1] == B.shape[0]):
        C = np.zeros((A.shape[1],B.shape[0]))
        
        for i in range(0,A.shape[0]):
            
            for j in range(0,B.shape[1]):
                
                sum = 0
                for k in range(0,A.shape[1]):
                    sum += A[i][k]*B[k][j]
                C[i][j] = sum
        return C
    
    
print(Mprod(A,B))
print("")
print(np.matmul(A,B))

[[23. 18. 62.]
 [36. 31. 98.]
 [11.  3. 85.]]

[[23 18 62]
 [36 31 98]
 [11  3 85]]


In [58]:
A = [[2,3,4],[5,4,6],[1,0,9]]
A = np.array(A)

def Mtrans(A):
    if (A.shape[0] == A.shape[1]):

        C = np.zeros(A.shape)
        
        for i in range(0,A.shape[0]):
            for j in range(0,A.shape[1]):
                C[i][j] = A[j][i]
        return C
    
print(A)
print("")
print(Mtrans(A))    

[[2 3 4]
 [5 4 6]
 [1 0 9]]

[[2. 5. 1.]
 [3. 4. 0.]
 [4. 6. 9.]]


In [59]:
def Mtraz(A):
    if (A.shape[0] == A.shape[1]):
        sum = 0
        for i in range(0,A.shape[0]):
            sum += A[i][i]
        return sum

print(A)
print("")
print(Mtraz(A))     

[[2 3 4]
 [5 4 6]
 [1 0 9]]

15


In [61]:
def DetCuad(A):
     if (A.shape[0] == A.shape[1]):
            D = A[0][0]*A[1][1]-A[0][1]*A[1][0]
            return D